[[template]]
  name = "jspm:generate"
  definition = """({ generatorEnv = ['browser', 'production', 'module'], ...generateOpts }) => [{
    deps: ['node_modules/@jspm/generator', 'node_modules/mkdirp'],
    engine: 'node',
    run: `
      import { Generator } from '@jspm/generator';
      import { readFile, writeFile } from 'fs/promises';
      import { pathToFileURL } from 'url';
      import mkdirp from 'mkdirp';
      import { dirname } from 'path';

      const generator = new Generator({
        mapUrl: pathToFileURL(process.env.TARGET),
        env: ${JSON.stringify(generatorEnv)}
      });

      const htmlSource = await readFile(process.env.DEP, 'utf-8');
      const outHtml = await generator.htmlGenerate(htmlSource, ${JSON.stringify(generateOpts)});

      mkdirp.sync(dirname(process.env.TARGET));
      await writeFile(process.env.TARGET, outHtml);
    `
  }, {
    template: 'npm:install',
    args: {
      packages: ['@jspm/generator', 'mkdirp'],
      dev: true
    }
  }]
  """
