[[template]]
name = "prettier"
definition = """({ name, targets, deps, env, options: { files = '.', check = false, write = true, config = null, noErrorOnUnmatchedPattern = false } }) => [{
  name,
  targets,
  deps: [...deps, 'node_modules/prettier'],
  env,
  run: `prettier ${files} ${
      check ? ' --check' : ''
    }${
      write ? ' --write' : ''
    }${
      config ? ` --config ${config}` : ''
    }${
      noErrorOnUnmatchedPattern ? ' --no-error-on-unmatched-pattern' : ''
    }`
}, {
  template: 'npm',
  options: {
    packages: ['prettier'],
    dev: true
  }
}]
"""
