name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build
      run: cargo build --verbose
    - name: Run Template Tests
      run: ../target/debug/chomp -c chomp-templates/chompfile.toml test
      env:
        CHOMP: "../target/debug/chomp"
